### ISSUE TITLE
SFTP outgoing methods not works if file day consists of two numbers and method use private method _parse_ls_line.

### ISSUE THREAD

**Issue by fenist19** [zatosource/zato#1102] opened 2020-11-30 14:13 UTC
```
30.11.2020 16:21:392020-11-30 16:21:39,126 - ERROR - 115:DummyThread-78148 - export_to_file_receiver:0 - list index out of range
30.11.2020 16:21:39Traceback (most recent call last):
30.11.2020 16:21:39  File "/opt/zato_dir/env/server/work/hot-deploy/current/file_receiver_services.py", line 50, in wrapper
30.11.2020 16:21:39    handle(self)
30.11.2020 16:21:39  File "/opt/zato_dir/env/server/work/hot-deploy/current/file_receiver_services.py", line 692, in handle
30.11.2020 16:21:39    self.save_file_to_sftp(file_receiver_conn, filename_on_upload_time, final_filename, backup_archive_name, buff,request_id)
30.11.2020 16:21:39  File "/opt/zato_dir/env/server/work/hot-deploy/current/file_receiver_services.py", line 779, in save_file_to_sftp
30.11.2020 16:21:39    file_receiver_conn.conn.write(buffer.getvalue(), name_on_upload, overwrite=True)
30.11.2020 16:21:39  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/sftp.py", line 621, in write
30.11.2020 16:21:39    self._overwrite_if_needed(remote_path, overwrite, log_level)
30.11.2020 16:21:39  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/sftp.py", line 595, in _overwrite_if_needed
30.11.2020 16:21:39    info = self.get_info(remote_path, log_level, raise_on_error=False)
30.11.2020 16:21:39  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/sftp.py", line 419, in get_info
30.11.2020 16:21:39    out = self._get_info(remote_path, log_level, raise_on_error=raise_on_error)
30.11.2020 16:21:39  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/sftp.py", line 413, in _get_info
30.11.2020 16:21:39    out = self._parse_ls_output(out.stdout) # type: List[SFTPInfo]
30.11.2020 16:21:39  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/sftp.py", line 399, in _parse_ls_output
30.11.2020 16:21:39    parsed = self._parse_ls_line(line)
30.11.2020 16:21:39  File "/opt/zato_dir/zato/code/zato-server/src/zato/server/connection/sftp.py", line 345, in _parse_ls_line
30.11.2020 16:21:39    name = line[1].strip()
30.11.2020 16:21:39IndexError: list index out of range
```
Error in method ### sftp._parse_ls_line
This exception rises in next line(example)
`-rw-------    ? 1014     100         30206 Nov 27 09:32 /dir/filename.zip`

Error in parser if one space between month and day.
If day consists of one number, `ls` command write two spaces , and method work correctly.
`-rw-------    1 1014     100       3635763 Nov  9 06:20 filename.zip`

**Comment by dsuch** [comment] 2020-11-30 14:17
Thanks, so just to confirm it, these will work:

* Nov 8
* Nov 9

But these will raise the exception:

* Nov 10
* Nov 25

Is that correct?

**Comment by fenist19** [comment] 2020-11-30 14:25
Yes please wait, I create PR with fix.

**Comment by fenist19** [comment] 2020-11-30 14:32
https://github.com/zatosource/zato/pull/1103

**Comment by dsuch** [comment] 2020-11-30 14:52
Thanks for the PR but I am not going to accept it. The issue is to do with parsing of a single element and you removed the whole method, including useful comments, instead leaving a regular expressions without any comments.

I will close the PR and work on the correct fix as soon as possible or you can work on it yourself but not in the way that you did it now. The only thing that needs to change is parsing of day, nothing else.

**Comment by dsuch** [comment] 2020-11-30 14:53
Also, in your PRs, do not use git commits such as "Fix <something>" because it does not describe anything really. Instead, describe what you did, e.g. "Made ls parsing handle two-digit days."

**Comment by dsuch** [comment] 2020-11-30 19:45
I am trying to reproduce it and so far I am unable to. I would like to confirm one thing - is the line below exactly what the parser cannot handle or is that a hand-written example?

``` -rw------- ? 1014 100 30206 Nov 27 09:32 /dir/filename.zip```

If this is an example, can you please post instead the actual line that cause the issues?

Thank you.

**Comment by dsuch** [comment] 2020-11-30 20:51
I was not able to reproduce it with single vs. double-digit days but I pushed a couple of related changes nevertheless. Can you install the latest updates and try again? Thanks.

https://zato.io/docs/admin/guide/install/update.html

**Comment by fenist19** [comment] 2020-12-02 13:57
Sorry, I use older branch.
Now problem with days that consists of one number. 
**Correct:**
> **input line**
> -rw-------    ? 1014     100         27158 Nov 20 14:38 /dir/file.zip
> **:329: line = line.split(' ', 3)  print** 
> ['Nov', '20', '14:38', '/dir/file.zip'] 
>  **:335: line = line[2:] print**
> ['14:38', '/dir/file.zip']

**Exception:**

>  **input line**
> -rw-------    ? 1014     100       3164060 Nov  2 15:58 /dir/file.zip
> **:329: line = line.split(' ', 3)  print** 
> ['Nov', '', '2', '15:58 /dir/file.zip']
> **:335: line = line[2:] print**
> 02.12.2020 14:11:25['15:58 /dir/file.zip']

after this exception in line
`344: line[1].strip()`



result after update https://github.com/zatosource/zato/pull/1104

> 02.12.2020 14:22:37-rw-------    ? 1014     100         27158 Nov 20 14:38 /dir/file.zip
> **:329: line = line.split(' ', 3)**
> 02.12.2020 14:22:37['Nov', '20', '14:38', '/dir/file.zip'] 

> 02.12.2020 14:22:37-rw-------    ? 1014     100       3164060 Nov  2 15:58 /dir/file.zip
> **:329: line = line.split(' ', 3)**
> 02.12.2020 14:22:37['Nov', '2', '15:58', '/dir/file.zip']

**Comment by dsuch** [comment] 2020-12-02 15:05
I pushed a new commit - can you check it, please?

**Comment by fenist19** [comment] 2020-12-03 05:27
It works.

**Comment by dsuch** [comment] 2020-12-03 15:52
Ok, I am closing the ticket in this case. Thanks.

**Closed by dsuch** 2020-12-03 15:52 UTC
