### ISSUE TITLE
Loaded services are not listed in web interface

### ISSUE THREAD

**Issue by InnokentyDM** [zatosource/zato#814] opened 2017-12-27 14:58 UTC
I can make channel using uploaded service, but it is not appear in admin web interface List Services.
Everything I made was installing Zato with docker and uploadinging simple service without any functionality.

**Comment by dsuch** [comment] 2017-12-27 16:51
Hello @InnokentyDM, please describe in detail:

* Your exact Zato version
* What exactly you have created and how (exact JSON requests and responses)
* What exactly you were expecting to appear in web-admin
* What exactly is appearing or not appearing in web-admin
* Where exactly in web-admin you are checking it

Regards.

**Comment by InnokentyDM** [comment] 2017-12-28 07:05
1) zato-2.0.8
2) I've created HTTP Basic Auth, Outgoing SOAP Connection (ping success), uploaded service and finally created SOAP Channel with this service.
`2017-12-28 06:29:30,721 - ^[[1;37mINFO^[[0m - 86:Dummy-188 - zato.hot-deploy.create:22 - Uploaded package id:[1], payload_name:[test_email.py]`
3) I was expecting to see uploaded service in List Services
4) After service uploading, success message appeared but service didn't appear in List Services
5) Services ---> List Services

**Comment by dsuch** [comment] 2017-12-28 12:31
Ok, can you also send in the service that you were uploading and confirm that you were uploading it from web-admin?

**Comment by InnokentyDM** [comment] 2017-12-28 13:26
It's just an example service. And yes I was uploading it from-admin

`from zato.server.service import Service

class MyService(Service):
    def handle(self):
        self.logger.info(type(self.request.raw_request))
        self.logger.info(self.request.raw_request)`

**Comment by InnokentyDM** [comment] 2018-01-10 13:36
Did you success in reproducing the issue?

**Comment by dsuch** [comment] 2018-01-10 14:12
Hi @InnokentyDM - there is a lot of work with preparing 3.0 and I did not have time for it yet. I asked a few people using 2.0.x and no one can reproduce it.

**Comment by InnokentyDM** [comment] 2018-01-11 14:43
@dsuch

Here is step by step instruction of what I've done. May be it will help to reproduce the issue.
1) I've done every command from https://zato.io/docs/admin/guide/install/docker.html
2) Login to zato web admin
3) Created HTTP Basic Auth and SOAP Outgoing Connection (ping successful)
4) Copied example service from https://zato.io/docs/progguide/service-dev.html to test_service.py 
5) Loaded service in web admin (loading successful, but List Service is empty)
6) Created Plain HTTP Channel with service 'test-service.my-service'

Also I made another one service. 
And it works fine except it is not shown in web admin. I can get data from it.

I've redone every step again and result the same.

**Comment by dsuch** [comment] 2018-01-20 10:40
Hello @InnokentyDM - I have just installed an environment like yours and I cannot reproduce the issue because there is no issue, it works as designed and documented.

Please consult the manual here: https://zato.io/docs/web-admin/services/main.html

```
Use ‘*’ to show all services or enter one or more parts of a service’s name. Keywords are AND-joined.
```

It means that if you would like to show all services you need to enter '*' (asterisk) and then choose "Show services" or you can enter parts of names, or an exact name, but you need to enter something.

Until you enter search criteria the search box shows a place-holder message "Enter * or part of a service's name, e.g. http json".

I am thus closing this ticket, feel free to reopen if you still have any issues.

Regards.

**Closed by dsuch** 2018-01-20 10:40 UTC
