### ISSUE TITLE
Kubernetes Documentation

### ISSUE THREAD

**Issue by techdragon** [zatosource/zato#881] opened 2018-09-06 02:11 UTC
Given the multi-service (Redis, Postgres, etc) nature of a Zato installation, It would be extremely useful to have documentation on how to run Zato on Kubernetes.

**Comment by kbni** [comment] 2018-09-06 14:20
Getting Zato running in Docker is super difficult, for a few reasons outlined on #515 (which I would suggest this issue is a duplicate of). But uh, I did have some success getting Zato running inside Docker: https://github.com/kbni/docker-zato

I built this whilst deploying Zato 3.0 for the first time, so I was unaware the scheduler was no longer attached to the singleton role, so there is no scheduler included. I'll update that repo soon with what I am currently using for Zato deployment.

**Comment by dsuch** [comment] 2018-09-06 16:44
@kbni Also, I have a general note. This is a ticket tracker used to publicly track issues and feature requests by a company producing software.

If you would like for something to be added, changed or otherwise given attention to then you need to be specific about what you need.

For instance, this is good and will result in someone treating your opinion with due consideration:

* I suggest adding a new feature ABC
* Can you add connections to system ABC?
* I would like for an existing feature ABC to be extended so it supported functionality ZXC
* Can you add documentation on how to achieve ABC?
* I have spotted such and such thing and I am not sure if this is expected or not?
* I do not understand how to do ABC, is it possible at all? Can you double-check if what I am doing is correct?
* I have an idea for a new feature ABC but I do not know how to implement it, can you assist me?
* I have implemented a new feature ABC - here it is in my repository - can you have a look at it?
* I would like to share a piece of software that I wrote - I hope/am sure someone will find it useful!

This can be accompanied by technical details but technical only, there is no need for any personal remarks or opinions about anything.

**Comment by kbni** [comment] 2018-09-06 23:40
@dsuch I'm sorry that you feel my response was not very informational. Other Zato users were interested in running Zato inside of containers, I only responded to share my experience with this regard in the hopes that it would be a useful starting point for them if they wanted to attempt to build their own containers. From my POV it seemed like there was not a lot of interest from the Zato team

I'm not familiar enough with Zato's internals to make anything other than vague suggestions, but from my experience I can tell you the server/load balancer/web interface relationship is what made building Docker images very difficult for me.

The current load balancer system does not seem very compatible with Docker networking, due to the requirement to know the IP of the host (which we don't) or the host (which we don't until the server container is actually created). 

I would suggest that a slightly easier approach would be to instead to have servers record their prescence in the ODB/KVDB and use this information to generate the load balancer configuration dynamically (this could be achieved using nginx/lua, I am unsure if this is possible with HAProxy). This is the aproach I am using for nameko-based microservices.

Honestly I am not entirely sure what real benefit is provided by signing the servers beyond that, if it just a matter of authentication I am sure using JWT or some other token-based authentication would suffice.

Creating a server component requires access to the ODB for which the server is going to be connected to, and if when building the image this is not available then the creation fails. Perhaps if servers were registered in a new way this would no longer be required?

Again, I don't feel I am qualified to provide the above feedback based on my limited knowledge of Zato internals but I hope the above is more useful, and less vague than my previous posts.

**Comment by techdragon** [comment] 2018-09-07 01:45
The current load balancer system already provides some primitives that will be useful in a Kubernetes environment. As described in #809 the existing load balancer uses a ping URL of `/zato/ping` to check if the individual servers are up. So a Kubernetes based environment should reuse this. In addition, the entire load balancing setup can be discarded, the servers can run with an alternative load balancer (such as the one Kubernetes would provide) this is also explained in #809. 

While Rancher is a Kubernetes based system, I'd like to make sure that this isn't considered a duplicate of #809 as I am specifically asking about expanding documentation (and potentially making code  improvements to better suit this mode of operation) on how to deploy Zato in a Kubernetes environment, where each of its architectural components is deployed, managed, and scaled by Kubernetes. To quote @dsuch, this is a variant of the following type of tickets. 
> - I would like for an existing feature ABC to be extended so it supported functionality ZXC
> - Can you add documentation on how to achieve ABC?

**Comment by dsuch** [comment] 2018-09-07 04:05
Various people have a lot of vastly different ideas about how to deploy their servers, including not using Docker at all, without Internet, or with very restricted networking, and Zato needs to take it all into account - I can assure you that there is interest in getting this ticket and related ones resolved.

1. Load-balancer can be always replaced by another one, this is correct. HAProxy has very interesting features outside of basic round-robin and a lot of people do not have any other load-balancer but if there is one, yes, the default one does not have to be used.

2. I contemplated the idea of getting servers register with the LB, and this is doable in principle, but there were a few changes required first.

2a. Most people bind servers to 0.0.0.0 and in Zato 2.0 there was no knowing what actual addresses they will use. In 3.0 a server has logic to check what its preferred address is from the perspective of an external client (which why there is now information such as  "Preferred address of `server1@quickstart-461471` (pid: 5637) is `http://192.168.0.39:17010`" in server logs). The preferred address can also be overridden explicitly in server.conf.

2b. Some people run load-balancers in DMZ and do not allow for servers to connect to load-balancers, it can be only the other way around.

3. I'm not sure what you mean by "signing servers beyond that", @kbni?

4. There are environments where adding a new server is a process that requires formal approval - this is why after you have added a server you need to go to web-admin and actually click in GUI to have it added to load-balancer's configuration and you cannot just add any server and have it join a cluster. I recognize that with Docker it is the other way around so there could be a flag in clusters to let them in without any confirmation.

5. If the flag from 4 above were enabled, there should be no obstacles to Docker image creation without access to ODB at the moment of when they are being created.

6. A feature that will be also added still to 3.0 are configuration variables read from environment.

For instance, in server.conf or other files instead of concrete values one will be able to use entries as below, resolved when needed (here, when a server starts):

```
[main]
gunicorn_bind=$server_address
```

6a. Environment variables will also cover entries created in web-admin / enmasse, e.g. REST or AMQP connections to external servers (external from a given system's perspective) with addresses driven by what a starting container presents in variables.

@techdragon - I understand that you would like to have documentation specific to Kubernetes and I am eager to do it as soon as possible but in the meantime, does the above information is in line with what you were expecting or wanted?

**Comment by techdragon** [comment] 2018-10-03 06:04
@dsuch thanks for confirming things and explaining some of your thoughts and planning for how to improve things in this direction. This is definitely in line with what I was expecting. 

Some feedback on the points you mentioned.
- I'm still unsure if the current behaviour of the server as you explained in 2a will cause any issues in a Docker/Kubernetes style environment. In such an environment, external clients should be talking to the load balancer which acts like a reverse proxy and from the point of view of the external client, all the servers are going to be indistinguishable, located at the same address and port. You mentioned that this preferred address can be overridden by the `server.conf` which will potentially solve the problem, but I'm still a little concerned since the existence of this logic as currently described, it implies that the client might under some circumstances want/try/need to talk to a specific server instance which could be a complication.
  - I've gone looking for references to this in the source code and from the look of it, this appears to be less about "*external* clients" and more about "*internal* clients". Since Kubernetes is designed to provide the supporting network for communicating between containers automatically, this shouldn't in theory be much of an issue if it is indeed meant for use between servers as these will be able to refer to each other using internal Kubernetes provided automatic IP/DNS naming. The only significant issue I spotted is that it appears that this information is sourced from the ODB which further highlights the need for better "automatic" cluster membership support, which is the very next point.    
- A flag/mechanism to enable 'auto join'  behaviour (like the ones mentioned in points 4 and 5) will definitely be needed in order to smoothly operate in Docker/Kubernetes style deployment/environments.
- completing work on the features you describe in 6/6a would (after improving the loadbalancer & cluster membership issues) probably be the final part needed to complete the kind of basic Kubernetes support I was hoping to see by opening this issue.
  - While Kubernetes has tooling to inject files into containers as part of deploying them, but not all Docker based systems have equivalent capabilities, and depending on the specific desired configuration, some blend of environment variables and configuration files may be required to achieve a desired result even in Kubernetes, so this is definitely needed, I would just prioritise it after the other work on cluster membership and loadbalancer configuration.

I hope the feedback is helpful.

**Comment by dsuch** [comment] 2019-01-26 08:38
Hello - this is just to let you know that the next release in June 2019 will have improved support for Docker Compose / Swarm / Kubernetes  and possibly other similar tools.

I will keep updating this ticket as needed - thanks.

**Comment by techdragon** [comment] 2019-01-27 13:00
@dsuch Thanks for the update. Is there anything I could do to help with the planned improvements? Im happy to help test deployments in Kubernetes.

**Comment by dsuch** [comment] 2019-01-27 15:39
Hi @techdragon - I will be starting with Compose and Swarm, followed by Kubernetes, so as to gradually handle more complex tools and cases.

For now I, can see that there is a bit of groundwork needed, such as:

* In Docker-based environments servers could auto-join clusters
* Configuration of connections, security definitions and other objects should be read from environment variables to be able to inject them when a container starts
* Images need to be created and published to Docker Hub with a standardized way to deploy services from file system (for which we [already](https://zato.io/docs/admin/guide/installing-services.html#service-sources-txt) have support)

There will be other internal changes required as well but the whole of it does not seem overwhelming.

**Comment by dsuch** [comment] 2019-05-21 19:07
Just to keep you updated, here are our Swarm, Kubernetes and quickstart implementations.

The former two are not documented yet, hence this is only an early preview. The final documentation will be available with Zato 3.1 release (June 2019).

The last one has been available for a while over at https://zato.io/docs/admin/guide/install/docker.html

* https://github.com/zatosource/zato-build/tree/master/docker/swarm
* https://github.com/zatosource/zato-build/tree/master/docker/kubernetes
* https://github.com/zatosource/zato-build/tree/master/docker/quickstart

**Comment by dsuch** [comment] 2019-06-17 16:20
Hello,

I am happy to let you know that starting with Zato 3.1 we now have images for Docker Quickstart, Swarm and Kubernetes. All of them are for Python 2.7 and 3.x.

https://zato.io/docs/admin/guide/install/index.html

Thank you for your contributions - I will close the ticket now, if there is a need for anything, please feel free to open a new one for a specific case needed.

**Closed by dsuch** 2019-06-17 16:20 UTC
