### ISSUE TITLE
error in server.log: Could not store mean/rate

### ISSUE THREAD

**Issue by catroot** [zatosource/zato#449] opened 2015-05-26 21:05 UTC
2015-05-26 23:54:11,759 - .[1;33mWARNING.[0m - 10524:Dummy-143631 - zato.stats.summary.create-summary-by-month:22 - Could not store mean/rate. e=`'Traceback (most recent call last):\n  File "/opt/zato/2.0.3/zato-erver/src/zato/server/service/internal/stats/summary.py", line 188, in create_summary\n    value = values[name]\nKeyError:u\'rate\'\n'`, locals=`{'pattern_names': (u'day', u'hour', u'minute'), 'stats': {u'usage': 203336, u'max': 470, u'rate': 0, u'mean':  1.9555555555555555, 1.9381944444444448, 1.9437499999999999, 1.9465277777777776, 1.939583333333333, 1.935239301253328, 1.9499999999999995, 1.9451388888888888, 1.95, 1.95, 1.9333.......`
and so on...
at the end of values:
 'e': KeyError(u'rate',), 'now': datetime.datetime(2015, 5, 26, 20, 52, 41, 678142), 'target': u'by-month', 'key_prefix': u'zato:stats:service:summary:by-month:', 'name': u'rate'}`

Zato installed with mysql backend.

**Comment by dsuch** [comment] 2015-05-27 09:23
Yes, this is a rather difficult to reproduce situation and it's not clear yet if it's harmless or not, hence it's a warning not an error. Most likely it's OK.

Thanks for sending it across!

**Comment by catroot** [comment] 2015-05-27 10:15
i`ts very clear situation. In file summaty.py, line 188:
                    for name in STATS_KEYS:
                        value = values[name]
error thrown tells us that there is no such key in values dict. should it be there or not - i can`t mention.
If there are a standart situation to query dict for unexisted keys - ok.
But catching an exception will be more likely.  
There can be a bug if key should exist, but doesn't.
Since the key name is rate, and i`ve just added a new service, and there are a part of statistic code - which is not collected yet in a right manner. 
Might be a proper zeroconf init for stats data will correct probability for that behaviour- because we must have stat key, but didnt have any value for it.

**Comment by catroot** [comment] 2015-05-31 12:11
Does this mean that i will miss my week, month and year summaries?

2015-05-30 09:53:49,497 - .[1;33mWARNING.[0m - 2955:Dummy-38519 - zato.stats.summary.create-summary-by-week:22 - Could not store mean/rate. 
2015-05-30 15:13:44,929 - .[1;33mWARNING.[0m - 2954:Dummy-55119 - zato.stats.summary.create-summary-by-week:22 - Could not store mean/rate. 
2015-05-30 20:53:52,036 - .[1;33mWARNING.[0m - 2955:Dummy-47746 - zato.stats.summary.create-summary-by-week:22 - Could not store mean/rate. 
2015-05-30 21:53:44,898 - .[1;33mWARNING.[0m - 2955:Dummy-48580 - zato.stats.summary.create-summary-by-week:22 - Could not store mean/rate. 
2015-05-31 01:54:44,163 - .[1;33mWARNING.[0m - 2954:Dummy-59900 - zato.stats.summary.create-summary-by-month:22 - Could not store mean/rate.
2015-05-31 14:53:52,446 - .[1;33mWARNING.[0m - 2955:Dummy-62977 - zato.stats.summary.create-summary-by-year:22 - Could not store mean/rate.

**Comment by dsuch** [comment] 2015-05-31 16:33
>  Could not store mean/rate. 

Is that the whole of the message? Was there any exception that you stripped off or that was it?

Thanks.

**Comment by catroot** [comment] 2015-05-31 19:49
e=`'Traceback (most recent c
all last):\n  File "/opt/zato/2.0.3/zato-server/src/zato/server/service/internal/stats/summary.py", line 188, in create_summary\n    value = values[name]\nKeyError:
There are a long dump of dict content
This is caused by the same thing as the problem i've started this issue from. The same missing key in dict at line 188.

**Comment by dsuch** [comment] 2015-05-31 20:34
Ok, thanks, like I said, this is a complex situation but I don't believe you will miss any summaries.

**Comment by catroot** [comment] 2015-05-31 21:27
ok. thanks.

**Comment by dsuch** [comment] 2015-06-15 12:44
Closing.

**Closed by dsuch** 2015-06-15 12:44 UTC

**Comment by gaaf** [comment] 2015-10-23 12:44
IMHO this is still a bug.

The failure is because the key "rate" is missing in the stats:
```
2015-10-23 13:15:39,977 - WARNING - 30815:Dummy-160513 - zato.stats.summary.create-summary-by-day:22 - Could not store mean/rate. e=`'Traceback (most recent call last):\n  File "/opt/zato/2.0.6/zato-server/src/zato/server/service/internal/stats/summary.py", line 188, in create_summary\n    value = values[name]\nKeyError: u\'rate\'\n'`, locals=
```

Stats are collected with:
`stats = self.collect_service_stats(elem, prefix, suffix, None, False, False, False)`
Note that the 7th parameter is False. This parameter is "needs_rate".


Something like this should fix it:
```
--- a/code/zato-server/src/zato/server/service/internal/stats/summary.py
+++ b/code/zato-server/src/zato/server/service/internal/stats/summary.py
@@ -185,7 +185,7 @@ class BaseSummarizingService(BaseAggregatingService):
                     stats = services.setdefault(service_name, deepcopy(DEFAULT_STATS))
 
                     for name in STATS_KEYS:
-                        value = values[name]
+                        value = values.get(name)
                         if name == 'usage':
                             stats[name] += value
                         elif name == 'max':
```
If "rate" is actually needed, changing the last False to True must also be added.
