### ISSUE TITLE
Three patches are not working anymore when installing from source

### ISSUE THREAD

**Issue by jjmurre** [zatosource/zato#750] opened 2017-02-23 12:28 UTC
When installing from source from the current main branch (at 95b581b8991eb39453fe65fd38392abd30546b10), buildout applies a series of patches.

Three of these patches are not working anymore:

Installing patch_gunicorn_logger.
patch: reading patch .../tst/zato-3/code/patches/gunicorn/glogging.py.diff
patch: total files: 1  total hunks: 2
patch: in .../tst/.buildout/eggs/gunicorn-18.0-py2.7.egg...
patch: processing 1/1:   .../tst/.buildout/eggs/gunicorn-18.0-py2.7.egg/gunicorn/glogging.py
patch: file is not patched - failed hunk: 2
patch: source file is different - .../tst/.buildout/eggs/gunicorn-18.0-py2.7.egg/gunicorn/glogging.py
While:
  Installing patch_gunicorn_logger.
Error: could not apply .../tst/zato-3/code/patches/gunicorn/glogging.py.diff

Installing patch_outbox.
patch: reading patch .../tst/zato-3/code/patches/outbox/outbox.py.diff
patch: total files: 1  total hunks: 4
patch: in .../tst/.buildout/eggs/outbox-0.1.8-py2.7.egg...
patch: processing 1/1:   .../tst/.buildout/eggs/outbox-0.1.8-py2.7.egg/outbox.py
patch: file is not patched - failed hunk: 4
patch: source file is different - .../tst/.buildout/eggs/outbox-0.1.8-py2.7.egg/outbox.py

Installing patch_outbox2.
patch: reading patch .../tst/zato-3/code/patches/outbox/outbox.py2.diff
patch: total files: 1  total hunks: 2
patch: in .../tst/.buildout/eggs/outbox-0.1.8-py2.7.egg...
patch: processing 1/1:   .../tst/.buildout/eggs/outbox-0.1.8-py2.7.egg/outbox.py
patch: file is not patched - failed hunk: 2
patch: source file is different - .../tst/.buildout/eggs/outbox-0.1.8-py2.7.egg/outbox.py

**Comment by dsuch** [comment] 2017-02-24 18:09
Hi @jjmurre,

can you please email me the offending files? The address is dsuch at zato.io

I'm on 95b581b8991eb39453fe65fd38392abd30546b10 too and cannot reproduce the situation:

```
Installing patch_gunicorn_logger.
patch: reading patch /home/dsuch/projects/zatosource-zato/code/patches/gunicorn/glogging.py.diff
patch: total files: 1  total hunks: 2
patch: in /home/dsuch/projects/zatosource-zato/code/eggs/gunicorn-18.0-py2.7.egg...
patch: processing 1/1:	 /home/dsuch/projects/zatosource-zato/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/glogging.py
patch: successfully patched /home/dsuch/projects/zatosource-zato/code/eggs/gunicorn-18.0-py2.7.egg/gunicorn/glogging.py


Installing patch_outbox2.
patch: reading patch /home/dsuch/projects/zatosource-zato/code/patches/outbox/outbox.py2.diff
patch: total files: 1  total hunks: 2
patch: in /home/dsuch/projects/zatosource-zato/code/eggs/outbox-0.1.8-py2.7.egg...
patch: processing 1/1:	 /home/dsuch/projects/zatosource-zato/code/eggs/outbox-0.1.8-py2.7.egg/outbox.py
patch: successfully patched /home/dsuch/projects/zatosource-zato/code/eggs/outbox-0.1.8-py2.7.egg/outbox.py
```

One thing that I have spotted though is the one below, can you reproduce it as well?

```
Installing patch_anyjson.
Not found: 
patch: reading patch /home/dsuch/projects/zatosource-zato/code/patches/anyjson/__init__.py.diff
patch: total files: 1  total hunks: 2
patch: in /home/dsuch/projects/zatosource-zato/code/eggs/anyjson-0.3.3-py2.7.egg...
patch: processing 1/1:	 /home/dsuch/projects/zatosource-zato/code/eggs/anyjson-0.3.3-py2.7.egg/anyjson/__init__.py
patch: successfully patched /home/dsuch/projects/zatosource-zato/code/eggs/anyjson-0.3.3-py2.7.egg/anyjson/__init__.py
```

**Comment by dsuch** [comment] 2017-02-24 20:32
Ok, I've just spent 2 hours trying to diagnose it and this ```Not found:``` message comes from setuptools and is not related to the patching process.

The reason was that we had find-links in buildout.cfg defined as:

```
find-links =
  https://launchpad.net/inotifyx/dev
  http://extlibs.zato.io/dependencies
```

This is per buildout's documentation but apparently setuptools prefers it to read as below:

```
find-links = https://launchpad.net/inotifyx/dev, http://extlibs.zato.io/dependencies
```

This was refactored in commit 423bdfdfe29054f3cdad0bf82db706a4e1103c17.

**Comment by jjmurre** [comment] 2017-02-25 15:24
That's totally weird and against the rules for a buildout files.
I tried it and als got these 'Not found' messages. And, the disappeared when I put find-links on one line, as you indicated. Seems to me either a setuptools bug, or something that buildout needs to fix.

**Comment by jjmurre** [comment] 2017-02-25 15:27
About my failing patches, I tried it on a totally clean vagrant box and the patches just work.
Maybe it has to do with the infrastructure, the server where I got these failing patches is on a very restricted environment. So we can close this issue I think.

**Comment by dsuch** [comment] 2017-02-25 15:38
Ok, thanks, I'm closing it in that case.

**Closed by dsuch** 2017-02-25 15:38 UTC
