### ISSUE TITLE
SQL notifications - output twice

### ISSUE THREAD

**Issue by orimani** [zatosource/zato#420] opened 2015-04-14 07:22 UTC
Hello,

I'm using Zato (docker) v2.0.2 and having an issue with the following spec:
- Outgoing SQL connection (poolsize 1)
- SQL Notifications (interval 60s etc + query)
- Service (default: Active + slow treshold 99999ms)

When SQL Notification return values, the Service parse the rows and then send it to a WebService (REST) to record a ticket.

It's working except that informations are logged twice and sent twice to the REST End-point (so I'm got twice ticket recorded).

Tell me if you need more informations.

Regards,
Mat

======

2015-04-09 10:23:27,992 DEBG 'zato-server2' stderr output:
2015-04-09 10:23:27,991 - INFO - 69:Dummy-110612 - zato.hot-deploy.create:22 - Creating tar archive

2015-04-09 10:23:27,995 DEBG 'zato-server1' stderr output:
2015-04-09 10:23:27,995 - INFO - 68:Dummy-111270 - zato.hot-deploy.create:22 - Creating tar archive

2015-04-09 10:23:28,003 DEBG 'zato-server2' stderr output:
2015-04-09 10:23:28,001 - INFO - 69:Dummy-110612 - zato.hot-deploy.create:22 - Creating tar archive

2015-04-09 10:23:28,012 DEBG 'zato-server1' stderr output:
2015-04-09 10:23:28,012 - INFO - 68:Dummy-111270 - zato.hot-deploy.create:22 - Creating tar archive

2015-04-09 10:23:28,101 DEBG 'zato-server2' stderr output
:2015-04-09 10:23:28,100 - INFO - 69:Dummy-110612 - zato.hot-deploy.create:22 - Uploaded package id:[9], payload_name:[centreonToSN.py]

2015-04-09 10:23:28,132 DEBG 'zato-server1' stderr output:
2015-04-09 10:23:28,132 - INFO - 68:Dummy-111270 - zato.hot-deploy.create:22 - Uploaded package id:[9], payload_name:[centreonToSN.py]

2015-04-09 10:23:33,014 DEBG 'redis' stdout output:
[10] 09 Apr 10:23:33.011 * 100 changes in 300 seconds. Saving...

2015-04-09 10:23:33,014 DEBG 'redis' stdout output:
[10] 09 Apr 10:23:33.012 * Background saving started by pid 2371

2015-04-09 10:23:33,306 DEBG 'redis' stdout output:
[2371] 09 Apr 10:23:33.305 * DB saved on disk

2015-04-09 10:23:33,307 DEBG 'redis' stdout output:
[2371] 09 Apr 10:23:33.307 * RDB: 3 MB of memory used by copy-on-write

2015-04-09 10:23:33,313 DEBG 'redis' stdout output:
[10] 09 Apr 10:23:33.313 * Background saving terminated with success

2015-04-09 10:23:56,484 DEBG 'zato-server2' stderr output:
2015-04-09 10:23:56,484 - INFO - 69:Dummy-110616 - centreon-to-sn.centreon-to-sn:22 - Logged twice

2015-04-09 10:23:57,497 DEBG 'zato-server1' stderr output:
2015-04-09 10:23:57,496 - INFO - 68:Dummy-111272 - centreon-to-sn.centreon-to-sn:22 - Logged twice

**Comment by dsuch** [comment] 2015-04-20 18:37
Hi @orimani,

there are two things here:

* ``` Creating tar archive``` -> this is displayed 4 times because you have 2 servers and each has 2 workers, i.e. it's OK that it's 4 times

* ``` Logged twice``` -> this one isn't correct - I'll see about it now

Thanks for reporting it, I'll be in touch.

**Comment by dsuch** [comment] 2015-04-20 19:03
By the way - why does it say **DEBG** instead of **DEBUG**, is it a typo in Docker?

**Comment by orimani** [comment] 2015-04-21 06:28
Hi @dsuch ,

Supervisord is running wth loglevel set to debug which is the root cause of all the lines with **DEBG** tag.
Sample of the Supervisord logs [here](https://github.com/Supervisor/supervisor/blob/master/docs/logging.rst).

**Comment by dsuch** [comment] 2015-04-21 09:12
> Supervisord is running wth loglevel set to debug
> which is the root cause of all the lines with DEBG tag

Ah, I get it, thanks.

Also, @orimani - I have confirmed the situation with notifications running twice and a fix is in progress. 

The reason was that each server was starting the notification machinery - this is incorrect, there should be only one instance of it in a whole cluster.

**Comment by dsuch** [comment] 2015-04-21 19:17
Fixed in this commit 7a26452c1f8ded1d2caa59aba05baf2bdc6c285d and ported to support/2.0 here 103ebdb3bace2e5f4536ccf8085881e42a91267e.

Will be released in 2.0.4.

Thanks heaps @orimani for reporting it!

**Closed by dsuch** 2015-04-21 19:17 UTC
Labels: 2.0.4
