### ISSUE TITLE
Could not create outgoing IBM MQ connection with version 3.2+rev.765a30d-py3.6.9

### ISSUE THREAD

**Issue by hondab** [zatosource/zato#1122] opened 2021-02-03 19:22 UTC
Hi,
Just installed a fresh version of zato3.2+rev.765a30d-py3.6.9 and I am successful in defining an IBM MQ Definition and also doing a Ping,, but when I try to define an Outbound MQ connection, I get the following Exception:

Could not create outgoing IBM MQ connection, e:`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/web/views/outgoing/jms_wmq.py", line 109, in create
    delivery_mode_text = delivery_friendly_name[int(req.POST['delivery_mode'])]
KeyError: 1

I am able to define Inbound MQ Connections and these work getting messages from the MQ Queue, so do not think there is anything missing from an MQ Setup point of view.

Please provide any advice on how to fix it or where to look for more info.

**Comment by dsuch** [comment] 2021-02-03 19:27
Hello @hondab,

thank you for opening the ticket - I am looking it at right now, I will keep you posted.

Just one question, what kind of an installation is it? From a .deb or .rpm package or under Docker?

It does not influence the current situation but installing updates differs depending on how you installed the platform so I would just like to confirm it.

Regards.

**Comment by dsuch** [comment] 2021-02-03 19:38
This is corrected, please install the latest updates per the instructions here:

https://zato.io/docs/admin/guide/install/update.html

Once you do it, please make sure to restart both the server and web-admin dashboard.

Next, you can confirm the installation by creating a new outgoing IBM MQ connection, clicking "Send a message" and, once it is created, filling out the form to send a message to your queue manager.

Thank you.

**Comment by hondab** [comment] 2021-02-03 22:59
HI
This is a deb install on Ubuntu 18 and the install was simple, and I
followed all the steps for setting the MQ env variable like export
LD_LIBRARY_PATH=/opt/mqm/lib64:/opt/mqm/lib:  in addition to set the
ibm_mq=true in the /opt/zato/esb/env3/server1/config/repo/server.conf.

Like I said, the Ping from the Definition works, and it is also able to
read MQ messages from the Channel->IBM_MQ just fine.. its only the
Outgoing-->IBM MQ that I am having an issue with.

[image: image.png]


[image: image.png]

**Comment by dsuch** [comment] 2021-02-03 23:01
Hello @hondab,

I am not sure if you saw my previous message, but I have already pushed a change to deal with this situation - please install the latest updates using the instructions here, making sure that you restart your server and web-admin dashboard afterwards:

https://zato.io/docs/admin/guide/install/update.html

**Comment by hondab** [comment] 2021-02-03 23:09
OK, applied the Fix, and It now allows me to Submit a message to the
Queue.. but it throws an Exception.

[image: image.png]

**Comment by dsuch** [comment] 2021-02-03 23:16
Please post the body of the exception as text, not as a screenshot, which does not display here.

**Comment by hondab** [comment] 2021-02-03 23:45
Here you go.

Caught an exception, e:`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/web/views/outgoing/jms_wmq.py",
line 177, in send_message_action
    response = req.zato.client.invoke('zato.outgoing.jms-wmq.send-message',
request)
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/middleware.py",
line 76, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'),
zato_env.get('details')))
Exception: CID: None
Details: None
`

**Comment by dsuch** [comment] 2021-02-03 23:51
Thanks, there will be details in /opt/zato/esb/env3/server1/logs/server.log - can you post it too?

**Comment by dsuch** [comment] 2021-02-03 23:52
Also, in addition to server.log there is a file called ibm-mq.log which may have details as well.

**Comment by hondab** [comment] 2021-02-04 13:10
See attached..

Caught an exception, e:`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/web/views/outgoing/jms_wmq.py",
line 177, in send_message_action
    response = req.zato.client.invoke('zato.outgoing.jms-wmq.send-message',
request)
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/middleware.py",
line 76, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(zato_env.get('cid'),
zato_env.get('details')))
Exception: CID: None
Details: None





Best Regards

Honda

**Comment by dsuch** [comment] 2021-02-04 13:13
Hello @hondab,

I am working on it as we speak - in the meantime, would it be possible for you to contact me on dsuch at zato.io?

Thank you.

**Comment by dsuch** [comment] 2021-02-04 22:18
Hello,

I have pushed changes related to this ticket - please install them using the same instructions as before:

https://zato.io/docs/admin/guide/install/update.html

**Comment by hondab** [comment] 2021-02-05 00:07
Caught an exception, e:`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/web/views/outgoing/jms_wmq.py",
line 177, in send_message_action
    response = req.zato.client.invoke('zato.outgoing.jms-wmq.send-message',
request)
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/middleware.py",
line 76, in invoke
    raise Exception('CID: {}\nDetails:
{}'.format(json_data.get('cid'), json_data.get('details')))
Exception: CID: b6b112b672c858d92b9e2edd
Details: Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py",
line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data,
path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py",
line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 749, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 702, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 588, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/service.py",
line 366, in handle
    response = func(id_, payload, channel, data_format, transport,
serialize=True)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 826, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name],
*args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 804, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 749, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 702, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 588, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/outgoing/jms_wmq.py",
line 229, in handle
    self.server.connector_ibm_mq.send_wmq_message(self.request.input)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/parallel/subprocess_/ibm_mq.py",
line 57, in send_wmq_message
    out = self.send_message(*args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py",
line 180, in send_message
    response = self.invoke_connector(msg)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py",
line 199, in invoke_connector
    raise Exception(response.text)
Exception: Exception in _on_OUTGOING_SEND (2) `Traceback (most recent
call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/connector/subprocess_/impl/ibm_mq.py",
line 327, in _on_OUTGOING_WMQ_SEND
    conn.send(text_msg, msg.queue_name)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/jms_wmq/jms/connection.py",
line 373, in send
    queue.put(body, md)
  File "/opt/zato/3.2.0/code/lib/python3.6/site-packages/pymqi/__init__.py",
line 1931, in put
    rv = pymqe.MQPUT(self.__qMgr.get_handle(), self.__qHandle,
m_desc.pack(), put_opts.pack(), msg)
  File "/opt/zato/3.2.0/code/lib/python3.6/site-packages/pymqi/__init__.py",
line 309, in pack
    ensure_not_unicode(v)  # Python 3 bytes check
  File "/opt/zato/3.2.0/code/lib/python3.6/site-packages/pymqi/__init__.py",
line 177, in ensure_not_unicode
    raise TypeError(msg.format(value))
TypeError: Python 3 style string (unicode) found but not allowed here:
`REPLY`. Convert to bytes.
`

`

Send a message using IBM MQ connection `My Outgoing CONN`

**Comment by hondab** [comment] 2021-02-05 00:09
Forgot to send logs..

**Comment by dsuch** [comment] 2021-02-05 00:09
I am not sure what the latest message is about? Can you please provide more context along with the output from zato --version? Thank you.

**Comment by hondab** [comment] 2021-02-05 18:32
The Version info is:

Zato 3.2+rev.8ef7775-py3.6.9

**Comment by hondab** [comment] 2021-02-05 18:35
~$ zato --version
Zato 3.2+rev.8ef7775-py3.6.9
zato@ravi-Virtual-Machine:~$ Zato 3.2+rev.8ef7775-py3.6.9

Getting the following Exception:

Caught an exception, e:`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/web/views/outgoing/jms_wmq.py",
line 177, in send_message_action
    response = req.zato.client.invoke('zato.outgoing.jms-wmq.send-message',
request)
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/middleware.py",
line 76, in invoke
    raise Exception('CID: {}\nDetails:
{}'.format(json_data.get('cid'), json_data.get('details')))
Exception: CID: fc6efb9c3600b36db6484200
Details: Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py",
line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data,
path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py",
line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 749, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 702, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 588, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/service.py",
line 366, in handle
    response = func(id_, payload, channel, data_format, transport,
serialize=True)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 826, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name],
*args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 804, in invoke_by_impl_name
    out = self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 749, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 702, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py",
line 588, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/outgoing/jms_wmq.py",
line 229, in handle
    self.server.connector_ibm_mq.send_wmq_message(self.request.input)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/parallel/subprocess_/ibm_mq.py",
line 57, in send_wmq_message
    out = self.send_message(*args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py",
line 180, in send_message
    response = self.invoke_connector(msg)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/connector/subprocess_/ipc.py",
line 199, in invoke_connector
    raise Exception(response.text)
Exception: Exception in _on_OUTGOING_SEND (2) `Traceback (most recent
call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/connector/subprocess_/impl/ibm_mq.py",
line 327, in _on_OUTGOING_WMQ_SEND
    conn.send(text_msg, msg.queue_name)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/jms_wmq/jms/connection.py",
line 373, in send
    queue.put(body, md)
  File "/opt/zato/3.2.0/code/lib/python3.6/site-packages/pymqi/__init__.py",
line 1931, in put
    rv = pymqe.MQPUT(self.__qMgr.get_handle(), self.__qHandle,
m_desc.pack(), put_opts.pack(), msg)
  File "/opt/zato/3.2.0/code/lib/python3.6/site-packages/pymqi/__init__.py",
line 309, in pack
    ensure_not_unicode(v)  # Python 3 bytes check
  File "/opt/zato/3.2.0/code/lib/python3.6/site-packages/pymqi/__init__.py",
line 177, in ensure_not_unicode
    raise TypeError(msg.format(value))
TypeError: Python 3 style string (unicode) found but not allowed here:
`REPLY`. Convert to bytes.
`

`

**Comment by dsuch** [comment] 2021-02-05 18:54
I cannot reproduce it - what other details are in the ibm-mq.log file? Also, what is the "REPLY" string that is mentioned in the exception?

**Comment by hondab** [comment] 2021-02-05 19:47
Hi Zatosource/Zato

The REPLY, is the value I set for the Reply To:  field.

If I remove it., everything works as expected. It only throws the Exception
when I have any string in that field.

Best Regards

Honda

**Comment by dsuch** [comment] 2021-02-07 19:47
Hello,

please install the latest updates and try again. Thank you.

https://zato.io/docs/admin/guide/install/update.html

**Comment by hondab** [comment] 2021-02-08 19:32
Thanks!

This is now working perfectly

[image: image.png]

**Comment by dsuch** [comment] 2021-02-08 19:34
Great, thanks for letting me know. Just one note - your inline screenshots do not display at all, when you reply in email using such screenshots, it is not possible to see them. Thank you again, I am closing the ticket.

**Closed by dsuch** 2021-02-08 19:34 UTC
