### ISSUE TITLE
pub/sub REST error on Zato 3.2.0

### ISSUE THREAD

**Issue by libigfat** [zatosource/zato#1151] opened 2021-04-09 03:43 UTC
My zato version Zato3.2+rev.8dfc912-py3.6.8

When I use zato3.2.0 to test the pub / sub rest interface, I strictly follow the documentation instructions.

![1](https://user-images.githubusercontent.com/40198012/114120536-41afac80-991f-11eb-97c9-ceb17a579120.png)

First, I created a topic

![1](https://user-images.githubusercontent.com/40198012/114120620-6b68d380-991f-11eb-89cd-0694bc62abb5.png)

Then I created an endpoint

![1](https://user-images.githubusercontent.com/40198012/114120747-acf97e80-991f-11eb-8e6e-f4ebe17fb79d.png)

And then I started testing every rest interface in the document

**1.Publication of messages | POST /zato/pubsub/topic//my/test**

![1](https://user-images.githubusercontent.com/40198012/114121390-dc5cbb00-9920-11eb-9c3e-6717d19a1c8f.png)

**Logs error**
```
2021-04-09 10:44:50,071 - [1;31mERROR[0m - 99493:DummyThread-586 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`ef88ad4dea77cf12b9aeca6c`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "src/zato/cy/bunch.pyx", line 12, in zato.bunch.Bunch.__getattr__
AttributeError: 'ServiceInput' object has no attribute 'sub_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/zato/cy/bunch.pyx", line 15, in zato.bunch.Bunch.__getattr__
KeyError: 'sub_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/zato/cy/simpleio.py", line 135, in zato.simpleio.ServiceInput.__getattr__
  File "src/zato/cy/bunch.pyx", line 17, in zato.bunch.Bunch.__getattr__
AttributeError: sub_key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 753, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 627, in _invoke
    service.http_method_handlers[service.request.http.method](service)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 154, in handle_POST
    if self.request.input.sub_key:
  File "src/zato/cy/simpleio.py", line 137, in zato.simpleio.ServiceInput.__getattr__
AttributeError: No such key `sub_key` among `{'topic_name': '/my/test', 'data': 'hello', 'priority': 2}
```

"Sub_key" should not be used when publishing messages. I feel that there is something wrong with this interface.

**2.Creating subscriptions | POST /zato/pubsub/subscribe/topic//my/test**

![1](https://user-images.githubusercontent.com/40198012/114122016-0793da00-9922-11eb-8296-077c3faf5b8a.png)

**Logs error**
```
2021-04-09 10:59:01,697 - [1;31mERROR[0m - 99493:DummyThread-601 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`5ce7e99bcc27b2ae85415e6a`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "src/zato/cy/bunch.pyx", line 12, in zato.bunch.Bunch.__getattr__
AttributeError: 'ServiceInput' object has no attribute 'delivery_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/zato/cy/bunch.pyx", line 15, in zato.bunch.Bunch.__getattr__
KeyError: 'delivery_method'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/zato/cy/simpleio.py", line 135, in zato.simpleio.ServiceInput.__getattr__
  File "src/zato/cy/bunch.pyx", line 17, in zato.bunch.Bunch.__getattr__
AttributeError: delivery_method

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 753, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 627, in _invoke
    service.http_method_handlers[service.request.http.method](service)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 202, in handle_POST
    'delivery_method': self.request.input.delivery_method or PUBSUB.DELIVERY_METHOD.PULL.id,
  File "src/zato/cy/simpleio.py", line 137, in zato.simpleio.ServiceInput.__getattr__
AttributeError: No such key `delivery_method` among `{'topic_name': '/my/test'}`
```

The document says **Applications creating subscriptions using this API are expected to periodically get their messages (pull-style)**, but why does this interface need a "delivery_method".

**3.Getting messages from queues | POST /zato/pubsub/topic//my/test?sub_key=**

Due to an error, I can't create a subscription using the rest interface. I don't have a "sub_key". So I choose to use web-admin to create a rest subscription manually to get a subkey to continue testing the interface.

![1](https://user-images.githubusercontent.com/40198012/114122924-dcaa8580-9923-11eb-887d-a9b1d044588e.png)

Now I get a "sub_key" manually

![1](https://user-images.githubusercontent.com/40198012/114123011-09f73380-9924-11eb-95fc-4d96a5cd445f.png)

Because there are errors in the publish message interface, I continue to use web-admin to publish new messages to endpoint, and then test the interface to get messages.
The method of using web-admin to publish message in document

![1](https://user-images.githubusercontent.com/40198012/114123540-16c85700-9925-11eb-81cb-35410a82a7bf.png)

My GD message 

![1](https://user-images.githubusercontent.com/40198012/114123702-6e66c280-9925-11eb-8c9a-65668ba86c47.png)

My RAM message

![1](https://user-images.githubusercontent.com/40198012/114123741-88080a00-9925-11eb-9149-7cccca55401f.png)

Then I immediately use the interface to get the two types of messages just released

**Getting messages from queues | POST /zato/pubsub/topic//my/test?sub_key=zpsk.rest.2e5750**

![1](https://user-images.githubusercontent.com/40198012/114124033-154b5e80-9926-11eb-9566-4686bf6b1e28.png)

But this interface returns an empty list. Did not receive the two types of information just released.
I checked the subscription page of webadmin and found the message displayed here.

![1](https://user-images.githubusercontent.com/40198012/114124353-d8339c00-9926-11eb-89a8-9ceb24c4e17d.png)

There are also these messages in the delivery task.

![1](https://user-images.githubusercontent.com/40198012/114124457-18931a00-9927-11eb-82ee-98e18b72658f.png)

But I can't get any message when I access the rest interface completely according to the method in the document. I have published several messages with different contents many times. The rest interface always returns an empty list without any content. Where is the message I published?

**4.Unsubscribing | DELETE /zato/pubsub/subscribe/topic//my/test?sub_key=zpsk.rest.2e5750**

![1](https://user-images.githubusercontent.com/40198012/114124809-d4ece000-9927-11eb-944c-446274abb210.png)

This is the only successful rest interface. It did unsubscribe.

**I think there are still a series of bugs in the sub / pub module of zato3.2. If they can be fixed, zato3.2 will become more stable.**
**Finally, thank you very much for creating zato, and I hope it will become better.**

**Comment by dsuch** [comment] 2021-04-09 08:40
Thank you very much for all your tickets and comments - all of this is very helpful and I truly appreciate it.

However, as I am involved in several projects and I work on other tickets too, I do not have time to use GitHub for work on this particular one because I was not able to reproduce it, i.e. I do not have time to exchange messages once in a while, check progress, ask for feedback etc.

This is why [I asked you](https://github.com/zatosource/zato/issues/1144#issuecomment-812658861) a few days ago to get in touch with directly for an alternative approach. Please contact me directly and in the meantime, I am closing this ticket. Thank you again for all your assistance.

**Closed by dsuch** 2021-04-09 08:40 UTC

**Comment by dsuch** [comment] 2021-05-05 18:54
Hello @libigfat - I am writing to ask if this is still an issue for you and you need assistance?

**Comment by libigfat** [comment] 2021-05-13 02:21
@dsuch yes,When I update zato to the latest version, I use the API interface to get messages from queries, and the log prompts an error.
```
2021-05-13 10:17:34,220 - [1;31mERROR[0m - 13845:DummyThread-189 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`9b809d54d54ad1b6f636b54a`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 748, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 622, in _invoke
    service.http_method_handlers[service.request.http.method](service)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 155, in handle_POST
    response = dumps(self._get_messages(endpoint_id))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 144, in _get_messages
    return self.pubsub.get_messages(self.request.input.topic_name, sub_key)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1766, in get_messages
    }, serialize=False)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1452, in invoke_service
    return self.server.invoke(name, msg, *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 934, in invoke
    *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1653, in invoke
    }, channel, None, needs_response=True, serialize=serialize, skip_response_elem=kwargs.get('skip_response_elem'))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1726, in on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 748, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 634, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/endpoint.py", line 687, in handle
    response = self.servers[sk_server.server_name].invoke(GetServerDeliveryMessages.get_name(), {
AttributeError: 'GetDeliveryMessages' object has no attribute 'servers'
```

**Comment by dsuch** [comment] 2021-05-16 19:08
@libigfat - Thanks for the message. I will let you know as soon as this is corrected.

**Comment by libigfat** [comment] 2021-05-21 07:40
@dsuch I update zato to the latest version, there is another error, when I use the API interface to get messages from queries
```
2021-05-21 15:35:01,895 - [1;31mERROR[0m - 13837:DummyThread-1031 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`8126e47073a94ea435f31057`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 748, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 622, in _invoke
    service.http_method_handlers[service.request.http.method](service)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 155, in handle_POST
    response = dumps(self._get_messages(endpoint_id))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 144, in _get_messages
    return self.pubsub.get_messages(self.request.input.topic_name, sub_key)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1766, in get_messages
    }, serialize=False)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1452, in invoke_service
    return self.server.invoke(name, msg, *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 934, in invoke
    *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1654, in invoke
    }, channel, None, needs_response=True, serialize=serialize, skip_response_elem=kwargs.get('skip_response_elem'))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1727, in on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 748, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 634, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/endpoint.py", line 692, in handle
    response = response['response']
TypeError: 'ServerInvocationResult' object is not subscriptable
```

**Comment by dsuch** [comment] 2021-05-21 07:42
@libigfat Can you please tell me what the exact URL that you are invoking is? Thank you.

**Comment by libigfat** [comment] 2021-05-21 09:11
@dsuch here is URL  POST http://192.168.204.139:17010/zato/pubsub/topic//test/?sub_key=zpsk.rest.22b39d

**Comment by dsuch** [comment] 2021-05-22 19:08
Could you please retry it, @libigfat?

Also, can you post the full output of the "zato --version" command?

Thank you.

**Comment by libigfat** [comment] 2021-05-25 05:15
@dsuch My zato version is Zato 3.2+rev.56d5090-py3.7.8-centos.7-core, and there is a new error.

```
2021-05-25 09:26:40,243 - [1;31mERROR[0m - 15692:DummyThread-127 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`635421b845c545af78a8088d`, status_code:`HTTPStatus.INTERNAL_SERVER_ERROR`, `Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 748, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 622, in _invoke
    service.http_method_handlers[service.request.http.method](service)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 155, in handle_POST
    response = dumps(self._get_messages(endpoint_id))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/pubapi.py", line 144, in _get_messages
    return self.pubsub.get_messages(self.request.input.topic_name, sub_key)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1766, in get_messages
    }, serialize=False)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/pubsub/__init__.py", line 1452, in invoke_service
    return self.server.invoke(name, msg, *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/parallel/__init__.py", line 937, in invoke
    *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1654, in invoke
    }, channel, None, needs_response=True, serialize=serialize, skip_response_elem=kwargs.get('skip_response_elem'))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/base/worker/__init__.py", line 1727, in on_message_invoke_service
    environ=msg.get('environ'))
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 806, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 748, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 634, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/pubsub/endpoint.py", line 692, in handle
    response = response['msg_list']
TypeError: 'ServerInvocationResult' object is not subscriptable
```

**Comment by dsuch** [comment] 2021-05-25 15:47
> TypeError: 'ServerInvocationResult' object is not subscriptable

Can you tell me how many servers you have in your cluster and how many processes there are per each server (main.gunicorn_workers in server.conf)?

Thank you.

**Comment by libigfat** [comment] 2021-05-26 02:02
@dsuch There is one server in my cluster and one process in per each server (gunicorn_workers=1)

**Comment by dsuch** [comment] 2021-06-07 07:17
Hello @libigfat - I am very interested in resolving it but I just cannot reproduce it locally.

It would be really good if you configured [ZeroTier](https://www.zerotier.com) on that instance and sent its ID to my email address (dsuch at zato.io). That will let me check directly what is happening.

Otherwise, I just cannot think of a way to reproduce it even if I am really trying to get to the root cause of it.

Regards.
