### ISSUE TITLE
'ResponseError: no such key' during server startup.

### ISSUE THREAD

**Issue by fklosowski** [zatosource/zato#194] opened 2014-04-11 13:28 UTC
Traceback (most recent call last):
  File "/home/ecgtheow/projects/fklosowski-zato/code/eggs/gevent-1.0-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/ecgtheow/projects/fklosowski-zato/code/zato-broker/src/zato/broker/client.py", line 67, in run
    self.on_message(Bunch(msg))
  File "/home/ecgtheow/projects/fklosowski-zato/code/zato-broker/src/zato/broker/client.py", line 165, in on_message
    self.kvdb.conn.rename(msg.data, tmp_key)
  File "/home/ecgtheow/projects/fklosowski-zato/code/eggs/redis-2.9.1-py2.7.egg/redis/client.py", line 853, in rename
    return self.execute_command('RENAME', src, dst)
  File "/home/ecgtheow/projects/fklosowski-zato/code/eggs/redis-2.9.1-py2.7.egg/redis/client.py", line 461, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/ecgtheow/projects/fklosowski-zato/code/eggs/redis-2.9.1-py2.7.egg/redis/client.py", line 471, in parse_response
    response = connection.read_response()
  File "/home/ecgtheow/projects/fklosowski-zato/code/eggs/redis-2.9.1-py2.7.egg/redis/connection.py", line 344, in read_response
    raise response
ResponseError: no such key

**Comment by dsuch** [comment] 2016-02-29 00:17
Thanks @fklosowski - closing now since it's been never reproduced.

**Closed by dsuch** 2016-02-29 00:17 UTC
