### ISSUE TITLE
MySQL Support and SQLAlchemy Error 1071 key was too long

### ISSUE THREAD

**Issue by brugr9** [zatosource/zato#1042] opened 2020-04-29 09:59 UTC
`zato quickstart create ~/esb/dge mysql localhost 6379 --verbose --odb_host localhost --odb_port 3307 --odb_user zato1 --odb_password mypwd --odb_db_name dgezato`

returns

`pymysql.err.InternalError: (1071, 'Specified key was too long; max key length is 3072 bytes')`

For MySQL database 'dgezato' default characterset is utf8mb4 and default collation is utf8mb4_0900_ai_ci
[zato.log](https://github.com/zatosource/zato/files/4550986/zato.log)

Kind regards, Roland

**Comment by dsuch** [comment] 2020-04-29 12:56
Hello @brugr9,

thank you for opening this ticket - I will try to have a look as soon as possible, so as to include it in Zato 3.2.

In the meantime, is using **utf8_unicode_ci** instead of **utf8mb4_0900_ai_ci** an option for you?

Regards.

**Comment by brugr9** [comment] 2020-04-29 13:54
Hi @dsuch,
same error using utf8_unicode_ci so far

**Comment by dsuch** [comment] 2020-04-29 14:01
Would it be, please, possible for you to catch the corresponding MySQL logs?

There seems to be an entry in one of indexes that is bigger than 768 or 1024 but I cannot really think of any of the built-in ones that should exceed it.

Particularly, because I am looking at an environment using utf8_unicode_ci as we speak.

**Comment by dsuch** [comment] 2020-06-24 17:28
Hello @brugr9 - does the situation still happen or can the ticket be closed? Thanks.

**Comment by dsuch** [comment] 2020-09-29 18:47
Hi @brugr9 - unfortunately, I have never been able to reproduce the case and I am closing the ticket. Please feel free to reopen any time.

**Closed by dsuch** 2020-09-29 18:47 UTC
