### ISSUE TITLE
Cannot hot-deploy the service

### ISSUE THREAD

**Issue by rashmireddy2719** [zatosource/zato#1066] opened 2020-07-16 21:57 UTC
When I try deploying the service using command line, the command executes and there is no information in the log. In the web-admin, I could see server has no deployment. The first deployment worked well and could see the source code in web-admin. From the later changes I am facing this issue. When trying to view the source : there is 500: server error

**Comment by dsuch** [comment] 2020-07-17 09:07
Hello,

I would like to help you but you do not provide any kind of details, no log files, no error messages, no Zato version, nothing.

I am closing the ticket because I cannot reproduce the situation. When you have the details, please feel free to reopen it with all the files uploaded.

Regards.

**Closed by dsuch** 2020-07-17 09:07 UTC
